#!/usr/bin/env python3
"""
Figure3d.py
===========
Quantitative support for the rank-1 backbone (highest-scoring path),
ready to drop into the manuscript text and as a small figure. Backbones
are obtained by brute-force enumeration of every simple root→terminal
path (the DAG is small — ≤25 paths/terminal). Path score = product of
edge supports along the path; scores are not probabilities and need not
sum to one across alternative paths.

For each terminal fate this computes:
  - backbone path score (rank 1, highest-scoring)
  - score of every alternative root→terminal path
  - per-edge support along the backbone
  - the number of OBLIGATE backbone steps (edges with support ≥ 0.99)

Two views are reported:
  (1) FULL path  — root→terminal, every edge included.
  (2) INTERNAL-only path — drops the first and last edges. These edges
      encode root prevalence and terminal cell-population frequencies
      rather than the fate-decision sequence proper.

Outputs:
  - Figure3d.png        — strip plot of ranked path scores, backbone
                           highlighted, per terminal

The numerical companion (Table 3) is generated by Table3.py.
"""

import os
import sys

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import networkx as nx
import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from _graph_utils import (
    compute_edge_supports, build_graph, _count_regions,
    _terminal_label, path_score, EDGES_CSV, TREES_CSV,
)


_HERE = os.path.dirname(os.path.abspath(__file__))
OUT_PNG = os.path.join(_HERE, "..", "figures", "Figure3d.png")

OBLIGATE_THRESHOLD = 0.99   # Edge is "obligate" if its edge support ≥ this

# Per-fate palette — matches k3_clustered_hierarchy_viz so panels read together
FATE_PALETTE = {
    "LV":    "#0057B8",
    "RV":    "#4DB6AC",
    "AVC":   "#E69F00",
    "AB":    "#D55E00",
    "Atria": "#CC79A7",
    "OFT":   "#00695C",
}


def _all_paths_to(G, root, term):
    return list(nx.all_simple_paths(G, root, term))


def _summarise(G, root, term):
    """Return a dict of summary numbers for one terminal."""
    paths = _all_paths_to(G, root, term)
    if not paths:
        return None

    probs_full = np.array([path_score(G, p) for p in paths])
    probs_int  = np.array([path_score(G, p, exclude_root_and_terminal=True)
                            for p in paths])
    order = np.argsort(probs_full)[::-1]
    backbone = paths[order[0]]
    backbone_edges = list(zip(backbone[:-1], backbone[1:]))
    backbone_p_each = [G.edges[u, v]["p"] for u, v in backbone_edges]
    n_obligate = sum(1 for p in backbone_p_each if p >= OBLIGATE_THRESHOLD)

    bb_full = probs_full[order[0]]
    bb_int  = probs_int [order[0]]
    return {
        "terminal":          _terminal_label(term),
        "n_paths":           len(paths),
        "backbone_path":     " → ".join(backbone),
        "backbone_p_full":   bb_full,
        "second_p_full":     probs_full[order[1]] if len(order) > 1 else 0.0,
        "total_mass_full":   probs_full.sum(),
        "dominance_full":    bb_full / probs_full.sum() if probs_full.sum() > 0 else 0.0,
        "margin_full":       bb_full / probs_full[order[1]] if len(order) > 1
                                                            and probs_full[order[1]] > 0 else float("inf"),
        "backbone_p_internal": bb_int,
        "second_p_internal":   sorted(probs_int, reverse=True)[1] if len(probs_int) > 1 else 0.0,
        "n_backbone_steps":   len(backbone_edges),
        "n_obligate_steps":   n_obligate,
        "backbone_edge_probs": ", ".join(f"{p:.2f}" for p in backbone_p_each),
        "backbone_edge_probs_list": backbone_p_each,
        "all_path_probs_full":     probs_full.tolist(),
        "all_path_probs_internal": probs_int.tolist(),
    }


def plot_panel(summaries):
    """Strip plot per terminal: ranked alternative path scores,
    backbone highlighted in orange, all others in light gray.

    Sized for ~1/3 of A4 width (≈70 mm) for Nat Cell Biol-style figure
    panel. Title is dropped — belongs in the figure caption.
    """
    n = len(summaries)
    fig, ax = plt.subplots(figsize=(2.0, 1.9), dpi=300)

    summaries = sorted(summaries, key=lambda s: -s["backbone_p_full"])
    y_pos = np.arange(n)

    # Determine x-range from data so we don't waste horizontal space
    max_p = max(np.array(s["all_path_probs_full"]).max() for s in summaries)
    x_max = max_p * 1.35  # leave room for the P=0.xx annotation

    rng = np.random.default_rng(0)
    for i, s in enumerate(summaries):
        probs = np.array(s["all_path_probs_full"])
        alt_probs = np.delete(probs, np.argmax(probs))
        alt_y = i + rng.uniform(-0.18, 0.18, size=len(alt_probs))
        ax.scatter(alt_probs, alt_y, c="#BBBBBB", s=8,
                   alpha=0.7, edgecolors="white", linewidths=0.2, zorder=3)
        ax.scatter([probs.max()], [i],
                   c="#E68A00", s=10, edgecolors="white",
                   linewidths=0.25, zorder=5)
        ax.text(probs.max() + max_p * 0.04, i,
                f"score={probs.max():.2f}",
                va="center", ha="left", fontsize=5, color="#333333")

    ax.set_yticks(y_pos)
    ax.set_yticklabels([s["terminal"] for s in summaries],
                       fontsize=6, fontweight="bold")
    ax.set_xlabel("Root → terminal path score",
                  fontsize=6)
    ax.set_xlim(0, x_max)
    ax.tick_params(axis="x", labelsize=5, pad=1.5, length=2.5, width=0.5)
    ax.tick_params(axis="y", length=0, pad=2)
    for spine in ["top", "right"]:
        ax.spines[spine].set_visible(False)
    ax.spines["bottom"].set_linewidth(0.5)
    ax.spines["left"].set_linewidth(0.5)
    ax.invert_yaxis()

    leg_handles = [
        plt.Line2D([0], [0], marker="o", color="w",
                   markerfacecolor="#E68A00", markeredgecolor="white",
                   markersize=3.2, label="Most probable"),
        plt.Line2D([0], [0], marker="o", color="w",
                   markerfacecolor="#BBBBBB", markeredgecolor="white",
                   markersize=3.2, label="Alternatives"),
    ]
    ax.legend(handles=leg_handles, fontsize=5, frameon=False,
              loc="upper left", bbox_to_anchor=(0.02, 0.98),
              ncol=1, handletextpad=0.25,
              borderpad=0.0, labelspacing=0.2)

    plt.tight_layout(pad=0.3)
    plt.savefig(OUT_PNG, dpi=300, bbox_inches="tight", facecolor="white")
    plt.close()
    print(f"✓ Saved: {OUT_PNG}")


def main():
    if not os.path.exists(EDGES_CSV) or not os.path.exists(TREES_CSV):
        print("ERROR: required CSVs not found")
        sys.exit(1)

    edge_support = compute_edge_supports()
    G = build_graph(edge_support)
    roots = [n for n in G.nodes if _count_regions(n) >= 6]
    terminals = [n for n in G.nodes if _count_regions(n) == 1]
    root = roots[0]

    summaries = []
    for term in sorted(terminals, key=_terminal_label):
        s = _summarise(G, root, term)
        if s:
            summaries.append(s)

    # Console summary
    print("\nPer-terminal backbone justification:\n")
    print(f"{'Terminal':<8} {'#paths':>7} {'BB full score':>14} {'2nd':>8} "
          f"{'margin':>7} {'BB int score':>13} {'oblig/total':>12} {'edges along BB':>30}")
    print("-" * 100)
    for s in summaries:
        margin = s["margin_full"]
        margin_str = f"{margin:.2f}×" if np.isfinite(margin) else "  inf"
        print(f"{s['terminal']:<8} {s['n_paths']:>7d} "
              f"{s['backbone_p_full']:>10.4f} {s['second_p_full']:>8.4f} "
              f"{margin_str:>7s} {s['backbone_p_internal']:>9.2f} "
              f"{s['n_obligate_steps']:>4d}/{s['n_backbone_steps']:<6d} "
              f"  {s['backbone_edge_probs']}")

    # Aggregate numbers for manuscript text
    means = {
        "BB full score":      np.mean([s["backbone_p_full"]     for s in summaries]),
        "BB internal score":  np.mean([s["backbone_p_internal"] for s in summaries]),
        "Margin (full)":      np.mean([s["margin_full"]         for s in summaries
                                      if np.isfinite(s["margin_full"])]),
        "Dominance (full)":   np.mean([s["dominance_full"]      for s in summaries]),
        "Obligate steps / total": (
            sum(s["n_obligate_steps"] for s in summaries) /
            sum(s["n_backbone_steps"] for s in summaries)
        ),
    }
    print("\n=== AGGREGATE NUMBERS for manuscript text ===")
    for k, v in means.items():
        if "Dominance" in k or "Obligate" in k:
            print(f"  {k:<28}: {v:.1%}")
        else:
            print(f"  {k:<28}: {v:.3f}")

    plot_panel(summaries)


if __name__ == "__main__":
    main()
